### PR TITLE
fix destruction code

### PR DESCRIPTION
**Pull request by kodram**
I think this code can cause destructive actions, such as:
- change the first element of the array @env["action_dispatch.request.formats"]

https://github.com/rails/rails/blob/7b667ec49a21120d431832a329a22d4c340e31d1/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L57

I think this method is less destructive

### CODE REVIEW

**Comment by kodram** [comment]
or maybe like this
```ruby
format = :xlsx
```

**Comment by straydogstudio** [comment]
True. It overwrites the first element of the array if it exists. But given the person has called `render :xlsx` to get here, is it significant? 

This code was for one purpose: Suppose a url "/foo/bar.html" was called, but the action left the request format unchanged and called `render xlsx: 'bar'`. Without populating the formats array the template would not be found. It's a fairly small use case which really shouldn't happen if things are done right. It might make better sense as `formats = [:xlsx]`.

Did you find a situation where losing the first format created a problem?

**Comment by kodram** [comment]
I was wrong, method *formats* is not from class ActionDispatch::Http::MimeNegotiation

this method from class ActionView::LookupContext

https://github.com/rails/rails/blob/f6797a7683e5367046217fa85900f0288a504f84/actionview/lib/action_view/lookup_context.rb#L55

you can see this: ActionView::Base.default_formats

default_formats set here

https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/actionpack/lib/action_dispatch.rb#L103

i.e. when ActiveSupport is load


Situation occurs when:

- header request contain 'HTTP_ACCEPT' => '\*/\*'
- if in Gemfile gem 'axlsx_rails' stored after gems which load ActiveSupport (devise, simple_form, gon, cancancan) then ActionView::Base.default_formats not contain *:xlsx*,


in the test, I emulated situation with format (the same effect is achieved if you can put in Gemfile gem who load ActiveSupport before axlsx_rails).

Sorry, I'm bad in english

**Comment by straydogstudio** [comment]
Thanks @kodram. I really appreciate the work. That makes it clear that [lines 7-9 in action_controller.rb](https://github.com/straydogstudio/axlsx_rails/blob/master/lib/axlsx_rails/action_controller.rb#L7-L9) are changing the default formats array between requests. 

Several things got cached in 4.2, one of which was the paths array which told Rails where to look for templates. axlsx_rails used to modify that too under certain circumstances, but [that had to be removed](https://github.com/straydogstudio/axlsx_rails#rails-42-changes). It looks like the default_formats array is also being cached. 

I think the best solution will be to remove lines 7-9 altogether. They really only support an unclear request. I think it is safe to assume people will include the format in their URLs. I am fairly sure messing with default_formats will come back to bite us later. Let me know if you think otherwise. 

I am going to keep your tests, however. It's worth having in the repo.

**Comment by kodram** [comment]
I agree with you. Please remove those lines.

**Comment by straydogstudio** [comment]
released a new version 0.4.0 with lines removed.

**Pull request merged**
