### PR TITLE
Add a testing section

### PR DESCRIPTION
**Pull request by sly7-7**
As asked in https://github.com/straydogstudio/axlsx_rails/issues/31#issuecomment-371884437 :smile:

### CODE REVIEW

**Comment by sly7-7** [comment]
@straydogstudio Here is it. Obviously, any suggestions are welcomed.

**Comment by straydogstudio** [comment]
@sly7-7 Thank you very much! I think it looks great. At some point I'll add some simple testing examples outside of RSpec also. No need for now though.

**Comment by sly7-7** [comment]
You're welcome :)

**Comment by sly7-7** [comment]
@straydogstudio Was it reopened on purpose ?

**Comment by straydogstudio** [comment]
Ha. I closed it before I merged it. I didn't realize it would remove the merge button if I closed it. :-0

**Comment by sly7-7** [comment]
Ha, ok, so nvm, I thought it was still open. I just forgot that merging automatically close the PR.

**Pull request merged**
