### PR TITLE
Lazy load with railtie / frozen_string_literal / latest ruby versions

### PR DESCRIPTION
**Pull request by ericproulx**
Hi,

Simply lazy_loading everything in `railtie`. I also added the meta `# frozen_string_literal: true` and I updated the ruby versions in `travis.yml`.

### CODE REVIEW

**Comment by straydogstudio** [comment]
Thanks for the work Eric. I'll get a good look at it in the next month.

**Comment by straydogstudio** [comment]
Thanks for the work on this @ericproulx. I've not done much with rail ties and lazy loading.

**Comment by ericproulx** [comment]
Thanks, do you know when you'll release v0.5.2 ?

**Comment by straydogstudio** [comment]
Sometime in the next few months. I may do it sooner to release the work you've done. Would that help you? If Axlsx gets a new release I will do it immediately to fix the Rubyzip dependency problems. Outside of the Rail tie, there really isn't much difference between master and 0.5.1.

**Comment by ericproulx** [comment]
It would help me but no stress.

**Pull request merged**
